use_modular_headers!
platform :ios, '9.0'

install! 'cocoapods', generate_multiple_pod_projects: true

target 'ModernWebToolKit_Example' do
  pod 'ModernWebToolKit', :path => '../'

  target 'ModernWebToolKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
